name: Deployment
on:
  workflow_dispatch:
    inputs:
      author:
        description: The owner of the deployment change
        required: false
        default: parcellab-dev-bot
      env:
        description: The environment where to deploy
        required: false
        default: test
      description:
        description: The information about the deployment change
        required: false
        default: Manual deployment in github actions
      ref:
        description: The github ref to deploy
        required: false
        default: $default-branch
jobs:
  from-dispatch:
    uses: parcelLab/.github/.github/workflows/deployment.yaml@v1
    with:
      author: ${{ github.event.inputs.author }}
      description: ${{ github.event.inputs.description }}
      env: ${{ github.event.inputs.env }}
      ref: ${{ github.event.inputs.ref }}
    secrets:
      repoAccessToken: ${{ secrets.REPO_ACCESS_TOKEN }}
