name: JSON
on:
  push:
    branches:
      - $default-branch
    paths:
      - "**.json"
  pull_request:
    paths:
      - "**.json"
  workflow_dispatch:
jobs:
  lint:
    uses: parcelLab/.github/.github/workflows/json.yaml@v1
