name: Shell
on:
  push:
    branches:
      - $default-branch
    paths:
      - "**.sh"
  pull_request:
    paths:
      - "**.sh"
  workflow_dispatch:
jobs:
  lint:
    uses: parcelLab/ci/.github/workflows/shell.yaml@v1
