name: PR
on:
  pull_request:
    types:
      - opened
      - edited
      - ready_for_review
      - reopened
      - synchronize
jobs:
  pr:
    uses: parcelLab/.github/workflow-reusables/pr.yaml@v1
    secrets:
      repoAccessToken: ${{ secrets.GITHUB_TOKEN }}
