name: Reusable PR
on:
  workflow_call:
    inputs:
      labelerConfig:
        required: false
        description: The folder that holds the labeler configuration
        default: .github/workflows/configs/labeler.yaml
        type: string
    secrets:
      repoAccessToken:
        required: true
        description: The Github token to perform operations cross-repo (can be secrets.GITHUB_TOKEN)
jobs:
  label:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Label PR based on pushed file paths
        continue-on-error: true
        uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.repoAccessToken }}
          configuration-path: ${{ inputs.labelerConfig }}
          sync-labels: true
